### ISSUE TITLE
DB Migration : ''Organization' cannot be used as a property on entity type 'ProductEntity' because it is configured as a navigation.'

### ISSUE THREAD

**Issue by fethibilog** [NetbootCommunity/MicroAutomation-Licensing#31]
this is what i did :
- i set the service project as the launch project
- changed ProviderType To SqlServer
- set ConnectionStrings both in appsettings.json and appsettings.Development.json
- finally i set IsStaging to false because i saw a condition disabling the migration code otherwise.

i'm i missing something?

Note : 
 i had an error with the connectionStrings parameter in DatabaseExtensions.cs but i switched the connectionStrings.DataProtectionDbConnection and connectionStrings.DataStoreDbConnection with the connection string "Server=localhost...". After that i got the same error 'Organization' cannot be used ...

**Comment by fethibilog** [comment]
Solution :
In ProductEntityBuilder.cs line 42 : replace Organization by OrganizationId
            .HasForeignKey(x => x.OrganizationId)
            
Afterwards do the usual :
- point your console on MicroAutomation.Licensing.Data.SQLServer
- Add-Migration -C <context>
- Fix import errors in the generated migration class
- Update-Database -Context <context>

**Comment by thomas-illiet** [comment]
Hello @fethibilog thx for this issue !!
actually i'm just running out of time unfortunately, i fix this project next week :)
